version: '3.9'

services:
  server:
    build: .
    ports:
      - '3000:3000'
  db:
    image: 'postgres'
    env_file: .env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
